//The first task is to make minigrep accept its two command line arguments: the filename and a string to search for. 
//That is, we want to be able to run our program with cargo run, a string to search for, and a path to a file to search in, like so:

//cargo run searchstring example-filename.txt

//Right now, the program generated by cargo new cannot process arguments we give it. Some existing libraries on crates.io 
//can help with writing a program that accepts command line arguments, but because you’re just learning this concept, let’s implement this capability ourselves.


//READING THE ARGUMENT VALUES
//To enable minigrep to read the values of command line arguments we pass to it, we’ll need a function provided in Rust’s standard library, which is std::env::args.
//This function returns an iterator of the command line arguments that were given to minigrep.
//For now, you only need to know two details about iterators: iterators produce a series of values, and we can call the collect method on an iterator 
//to turn it into a collection, such as a vector, containing all the elements the iterator produces.

//check main.rs